import {
  AIHazard,
  AIDispatchRecommendation,
  VerificationReport,
  AIInsightsData,
  ParsedIncident,
} from "@/types/ai";

export const MOCK_AI_INSIGHTS: AIInsightsData = {
  criticalIncidents: 6,
  averageEtaMinutes: 4.8,
  averageConfidencePercentage: 94.2,
  verificationSuccessPercentage: 98.6,
  predictedCongestionLevel: "Moderate",
  activeUnitsDeployed: 14,
};

export const MOCK_HAZARDS: AIHazard[] = [
  {
    id: "HZ-801",
    title: "Multi-Vehicle Collision near Gachibowli Flyover",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "2 mins ago",
    location: "Gachibowli Flyover North Ramp, Hyderabad",
    description: "Two heavy commercial buses and a sedan collided blocking main arterial lanes. Fuel leak detected on asphalt.",
    verificationPercentage: 96,
    source: "CCTV AI Vision",
    status: "Active",
    coordinates: { lat: 17.4401, lng: 78.3489 },
    vehiclesInvolved: "2 Buses, 1 Sedan",
    blockedLanes: "2 of 3 Lanes Blocked",
    victimsEstimated: 5,
  },
  {
    id: "HZ-802",
    title: "Rollover Crash on Outer Ring Road Exit 3",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "5 mins ago",
    location: "ORR Exit 3 Narsingi Interchange",
    description: "SUV lost control at high speed and rolled over into embankment. Passengers trapped inside cabin.",
    verificationPercentage: 98,
    source: "Citizen Mobile App",
    status: "Dispatched",
    coordinates: { lat: 17.385, lng: 78.3611 },
    vehiclesInvolved: "1 SUV",
    blockedLanes: "Right Shoulder Blocked",
    victimsEstimated: 3,
  },
  {
    id: "HZ-803",
    title: "Oil Spill & Multi-Bike Skids on Cyber Towers Underpass",
    priority: "P2 - High",
    severity: "High",
    timestamp: "8 mins ago",
    location: "Hitec City Cyber Towers Underpass",
    description: "Diesel leakage from a freight delivery vehicle created hazardous slick road surface resulting in minor skids.",
    verificationPercentage: 91,
    source: "Traffic Sensor IoT",
    status: "Investigating",
    coordinates: { lat: 17.4504, lng: 78.3808 },
    vehiclesInvolved: "1 Freight Truck, 2 Motorcycles",
    blockedLanes: "Underpass Westbound Closed",
    victimsEstimated: 2,
  },
  {
    id: "HZ-804",
    title: "Pedestrian Knockdown at Mindspace Junction",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "11 mins ago",
    location: "Mindspace IT Park Signal 2",
    description: "High speed cab struck pedestrian near crossing zone. Emergency medical intervention requested by bystanders.",
    verificationPercentage: 99,
    source: "911 Emergency Call",
    status: "Dispatched",
    coordinates: { lat: 17.4416, lng: 78.3826 },
    vehiclesInvolved: "1 Hatchback",
    blockedLanes: "Left Lane Blocked",
    victimsEstimated: 1,
  },
  {
    id: "HZ-805",
    title: "Cargo Truck Mechanical Breakdown & Hazard Signal",
    priority: "P3 - Standard",
    severity: "Moderate",
    timestamp: "15 mins ago",
    location: "Kondapur Main Road near Botanical Garden",
    description: "Axle failure on heavy transport truck blocking center lane causing progressive back-up toward Kothaguda.",
    verificationPercentage: 88,
    source: "Police Radio Dispatch",
    status: "Active",
    coordinates: { lat: 17.4568, lng: 78.3672 },
    vehiclesInvolved: "1 Container Truck",
    blockedLanes: "Center Lane Blocked",
    victimsEstimated: 0,
  },
  {
    id: "HZ-806",
    title: "Electric Auto-Rickshaw Thermal Runaway Event",
    priority: "P2 - High",
    severity: "High",
    timestamp: "18 mins ago",
    location: "Financial District Phase 2 Flyover",
    description: "Battery enclosure smoke emission and localized fire on EV auto. Fire tender and trauma unit notified.",
    verificationPercentage: 94,
    source: "CCTV AI Vision",
    status: "Active",
    coordinates: { lat: 17.414, lng: 78.3444 },
    vehiclesInvolved: "1 EV Auto",
    blockedLanes: "Slip Road Blocked",
    victimsEstimated: 1,
  },
  {
    id: "HZ-807",
    title: "Water Pipeline Rupture & Road Collapse",
    priority: "P2 - High",
    severity: "High",
    timestamp: "22 mins ago",
    location: "Jubilee Hills Road No. 36 Signal",
    description: "Burst main line caused asphalt wash-out and large sinkhole. Traffic diverted to Road 45 link.",
    verificationPercentage: 90,
    source: "Traffic Sensor IoT",
    status: "Investigating",
    coordinates: { lat: 17.4326, lng: 78.4071 },
    vehiclesInvolved: "None",
    blockedLanes: "All Lanes Southbound Blocked",
    victimsEstimated: 0,
  },
  {
    id: "HZ-808",
    title: "Chain Collision 4 Cars near Bio-Diversity Park",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "25 mins ago",
    location: "Bio-Diversity Park Flyover Ramp",
    description: "Sudden braking on ramp led to rear-end impact chain reaction across 4 passenger sedans.",
    verificationPercentage: 97,
    source: "Citizen Mobile App",
    status: "Dispatched",
    coordinates: { lat: 17.4379, lng: 78.3842 },
    vehiclesInvolved: "4 Passenger Sedans",
    blockedLanes: "2 Lanes Blocked",
    victimsEstimated: 4,
  },
  {
    id: "HZ-809",
    title: "Fallen Construction Crane Barrier",
    priority: "P3 - Standard",
    severity: "Moderate",
    timestamp: "30 mins ago",
    location: "Kukatpally Y Junction Flyover",
    description: "Heavy wind displaced metal staging barrier into active traffic lane causing slow moving congestion.",
    verificationPercentage: 85,
    source: "Police Radio Dispatch",
    status: "Active",
    coordinates: { lat: 17.4842, lng: 78.4069 },
    vehiclesInvolved: "None",
    blockedLanes: "Left Lane Blocked",
    victimsEstimated: 0,
  },
  {
    id: "HZ-810",
    title: "Medical Emergency Inside Transit Bus",
    priority: "P2 - High",
    severity: "High",
    timestamp: "34 mins ago",
    location: "Miyapur Metro Station Depot Exit",
    description: "Bus driver pulled over after passenger experienced acute cardiac distress. EMS dispatched.",
    verificationPercentage: 95,
    source: "911 Emergency Call",
    status: "Dispatched",
    coordinates: { lat: 17.4966, lng: 78.3614 },
    vehiclesInvolved: "1 Metro Express Bus",
    blockedLanes: "Bus Bay Occupied",
    victimsEstimated: 1,
  },
  {
    id: "HZ-811",
    title: "Signal Controller Failure & Blind Intersection Risk",
    priority: "P3 - Standard",
    severity: "Moderate",
    timestamp: "40 mins ago",
    location: "Madhapur Police Station Junction",
    description: "Traffic light matrix blacked out due to local grid trip. High risk of T-bone collisions.",
    verificationPercentage: 92,
    source: "Traffic Sensor IoT",
    status: "Investigating",
    coordinates: { lat: 17.4486, lng: 78.3908 },
    vehiclesInvolved: "N/A",
    blockedLanes: "Intersection Uncontrolled",
    victimsEstimated: 0,
  },
  {
    id: "HZ-812",
    title: "Hazardous Chemical Tanker Leak Alert",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "45 mins ago",
    location: "Patancheru Industrial Area Entry Gate 1",
    description: "Pressurized valve leak on industrial ammonia tanker. Hazmat perimeter and evacuation initiated.",
    verificationPercentage: 99,
    source: "CCTV AI Vision",
    status: "Dispatched",
    coordinates: { lat: 17.5302, lng: 78.2635 },
    vehiclesInvolved: "1 Chemical Tanker",
    blockedLanes: "Both Directions Closed",
    victimsEstimated: 2,
  },
  {
    id: "HZ-813",
    title: "Stalled Metro Feed Feeder Bus Blocking Ramp",
    priority: "P4 - Low",
    severity: "Low",
    timestamp: "50 mins ago",
    location: "Raidurg Metro Station Concourse Drop",
    description: "Overheated radiator forced bus to stop at drop-off zone. Tow truck unit assigned.",
    verificationPercentage: 89,
    source: "Citizen Mobile App",
    status: "Active",
    coordinates: { lat: 17.4429, lng: 78.3772 },
    vehiclesInvolved: "1 Feeder Bus",
    blockedLanes: "1 Drop Lane Blocked",
    victimsEstimated: 0,
  },
  {
    id: "HZ-814",
    title: "Motorcycle T-Bone Crash at Inorbit Mall Circle",
    priority: "P2 - High",
    severity: "High",
    timestamp: "55 mins ago",
    location: "Inorbit Mall Entrance Road",
    description: "Two-wheeler struck by turning SUV at moderate velocity. Rider conscious with limb injuries.",
    verificationPercentage: 93,
    source: "CCTV AI Vision",
    status: "Dispatched",
    coordinates: { lat: 17.4382, lng: 78.3888 },
    vehiclesInvolved: "1 SUV, 1 Motorcycle",
    blockedLanes: "Right Turning Lane Blocked",
    victimsEstimated: 1,
  },
  {
    id: "HZ-815",
    title: "Tree Limb Down Across Highway Medians",
    priority: "P4 - Low",
    severity: "Low",
    timestamp: "1 hr ago",
    location: "Begumpet Airport Outer Wall Road",
    description: "Branch fell onto outer lane following localized rain squall. Road clearing team en route.",
    verificationPercentage: 87,
    source: "Police Radio Dispatch",
    status: "Resolved",
    coordinates: { lat: 17.4468, lng: 78.4678 },
    vehiclesInvolved: "None",
    blockedLanes: "Far Left Lane Cleared",
    victimsEstimated: 0,
  },
  {
    id: "HZ-816",
    title: "Submerged Roadway under Expressway Underpass",
    priority: "P2 - High",
    severity: "High",
    timestamp: "1 hr ago",
    location: "Tolichowki Flyover Underpass",
    description: "Storm drain blockage caused 1.5 ft water logging stalling low clearance vehicles.",
    verificationPercentage: 91,
    source: "Traffic Sensor IoT",
    status: "Resolved",
    coordinates: { lat: 17.3986, lng: 78.4168 },
    vehiclesInvolved: "2 Compact Cars Stalled",
    blockedLanes: "Underpass Diverted",
    victimsEstimated: 0,
  },
  {
    id: "HZ-817",
    title: "Commercial Van Brake Failure & Guardrail Strike",
    priority: "P2 - High",
    severity: "High",
    timestamp: "1.5 hrs ago",
    location: "Punjagutta Flyover Center Curve",
    description: "Delivery van struck concrete divider wall at curve. Driver sustained mild trauma.",
    verificationPercentage: 96,
    source: "911 Emergency Call",
    status: "Resolved",
    coordinates: { lat: 17.4262, lng: 78.4533 },
    vehiclesInvolved: "1 Commercial Van",
    blockedLanes: "Fast Lane Cleared",
    victimsEstimated: 1,
  },
  {
    id: "HZ-818",
    title: "High Voltage Cable Dropped onto Roadway",
    priority: "P1 - Immediate",
    severity: "Critical",
    timestamp: "2 hrs ago",
    location: "Banjara Hills Road No. 12 Intersection",
    description: "Live utility wire snapped off pole after utility truck snagged cable. Utility safety team secured grid.",
    verificationPercentage: 100,
    source: "Police Radio Dispatch",
    status: "Resolved",
    coordinates: { lat: 17.4158, lng: 78.4419 },
    vehiclesInvolved: "1 Utility Truck",
    blockedLanes: "Road Fully Reopened",
    victimsEstimated: 0,
  },
  {
    id: "HZ-819",
    title: "Debris Container Spill on PVNR Expressway",
    priority: "P3 - Standard",
    severity: "Moderate",
    timestamp: "2.5 hrs ago",
    location: "PVNR Expressway Pillar 120",
    description: "Gravel cargo shed cover ripped open dropping aggregate across 200 meters of elevated express corridor.",
    verificationPercentage: 88,
    source: "CCTV AI Vision",
    status: "Resolved",
    coordinates: { lat: 17.3712, lng: 78.4325 },
    vehiclesInvolved: "1 Tipper Truck",
    blockedLanes: "Expressway Swept & Clear",
    victimsEstimated: 0,
  },
  {
    id: "HZ-820",
    title: "Two Wheelers Slip on Wet Paint Markings",
    priority: "P4 - Low",
    severity: "Low",
    timestamp: "3 hrs ago",
    location: "Koti Women's College Traffic Circle",
    description: "Fresh road marking paint without friction beads caused minor low speed skid. Area re-tackified.",
    verificationPercentage: 84,
    source: "Citizen Mobile App",
    status: "Resolved",
    coordinates: { lat: 17.3824, lng: 78.4851 },
    vehiclesInvolved: "2 Scooters",
    blockedLanes: "Circle Clear",
    victimsEstimated: 0,
  },
];

export const MOCK_DISPATCH_RECOMMENDATIONS: AIDispatchRecommendation[] = [
  {
    id: "REC-101",
    hazardId: "HZ-801",
    recommendedAmbulance: "ALS Advanced Unit A04",
    unitId: "AMB-A04",
    distanceKm: 1.8,
    etaMinutes: 3.2,
    recommendedHospital: "AIG Hospitals Gachibowli",
    hospitalOccupancy: "Low",
    reasoning: "Ambulance A04 selected because it is closest (1.8km), traffic density on Financial District road is moderate, and AIG Emergency Department has 8 available ICU beds.",
    confidenceScore: 97.4,
    status: "Pending",
  },
  {
    id: "REC-102",
    hazardId: "HZ-802",
    recommendedAmbulance: "Trauma Response Unit T02",
    unitId: "AMB-T02",
    distanceKm: 2.9,
    etaMinutes: 4.5,
    recommendedHospital: "Care Hospitals Narsingi",
    hospitalOccupancy: "Moderate",
    reasoning: "Trauma Unit T02 is equipped with heavy hydraulic extrication kit needed for rollover rescue; direct expressway access provides green-corridor ETA of 4.5 mins.",
    confidenceScore: 98.1,
    status: "Dispatched",
  },
  {
    id: "REC-103",
    hazardId: "HZ-803",
    recommendedAmbulance: "Rapid Response Bike Unit R08",
    unitId: "AMB-R08",
    distanceKm: 0.9,
    etaMinutes: 2.1,
    recommendedHospital: "Medicover Hospitals Hitec City",
    hospitalOccupancy: "Low",
    reasoning: "Rapid bike unit selected to bypass stuck underpass queue with first-responder burn/trauma medical kits while heavy ambulance stands by on peripheral road.",
    confidenceScore: 92.5,
    status: "Pending",
  },
  {
    id: "REC-104",
    hazardId: "HZ-804",
    recommendedAmbulance: "Cardiac ALS Unit A12",
    unitId: "AMB-A12",
    distanceKm: 1.4,
    etaMinutes: 2.8,
    recommendedHospital: "Yashoda Hospitals Hitec City",
    hospitalOccupancy: "Low",
    reasoning: "ALS Unit A12 is positioned 1.4km away with direct line-of-sight signal preemption capabilities along Mindspace main avenue.",
    confidenceScore: 99.0,
    status: "Dispatched",
  },
  {
    id: "REC-105",
    hazardId: "HZ-805",
    recommendedAmbulance: "Standard BLS Unit B03",
    unitId: "AMB-B03",
    distanceKm: 3.5,
    etaMinutes: 6.0,
    recommendedHospital: "KIMS Hospital Kondapur",
    hospitalOccupancy: "Moderate",
    reasoning: "Precautionary BLS unit staged near Kondapur RTA junction due to zero casualty reports, maintaining high-tier ALS units free for priority calls.",
    confidenceScore: 89.2,
    status: "Pending",
  },
  {
    id: "REC-106",
    hazardId: "HZ-806",
    recommendedAmbulance: "Hazmat Paramedic Unit H01",
    unitId: "AMB-H01",
    distanceKm: 2.2,
    etaMinutes: 4.0,
    recommendedHospital: "Continental Hospitals Nanakramguda",
    hospitalOccupancy: "Low",
    reasoning: "Specialized EV thermal burn unit dispatched with chemical respiration gear and direct routing via Financial District arterial road.",
    confidenceScore: 94.8,
    status: "Pending",
  },
  {
    id: "REC-107",
    hazardId: "HZ-807",
    recommendedAmbulance: "Standby Medic Unit S05",
    unitId: "AMB-S05",
    distanceKm: 4.1,
    etaMinutes: 7.5,
    recommendedHospital: "Apollo Hospitals Jubilee Hills",
    hospitalOccupancy: "High",
    reasoning: "Staged near Road 36 detour route to handle potential secondary motorist collisions during heavy rush hour diversion.",
    confidenceScore: 88.0,
    status: "Pending",
  },
  {
    id: "REC-108",
    hazardId: "HZ-808",
    recommendedAmbulance: "Multi-Patient Transit Unit M02",
    unitId: "AMB-M02",
    distanceKm: 2.0,
    etaMinutes: 3.8,
    recommendedHospital: "Star Hospitals Nanakramguda",
    hospitalOccupancy: "Low",
    reasoning: "M02 multi-stretcher ambulance dispatched to accommodate up to 4 simultaneous injuries from 4-car chain collision.",
    confidenceScore: 96.7,
    status: "Dispatched",
  },
  {
    id: "REC-109",
    hazardId: "HZ-809",
    recommendedAmbulance: "BLS Support Unit B07",
    unitId: "AMB-B07",
    distanceKm: 3.8,
    etaMinutes: 6.5,
    recommendedHospital: "Kukatpally Prime Hospital",
    hospitalOccupancy: "Low",
    reasoning: "Staged at Y-junction overpass as barrier clearance operations proceed.",
    confidenceScore: 86.4,
    status: "Pending",
  },
  {
    id: "REC-110",
    hazardId: "HZ-810",
    recommendedAmbulance: "Cardiac Specialist Unit C01",
    unitId: "AMB-C01",
    distanceKm: 1.1,
    etaMinutes: 2.3,
    recommendedHospital: "Malla Reddy Narayana Hospital",
    hospitalOccupancy: "Low",
    reasoning: "Specialized cardiac telemedicine unit dispatched to Miyapur bus bay with instant ecg telemetry linked to emergency department.",
    confidenceScore: 98.4,
    status: "Dispatched",
  },
  {
    id: "REC-111",
    hazardId: "HZ-811",
    recommendedAmbulance: "Patrol Medic Unit P04",
    unitId: "AMB-P04",
    distanceKm: 2.7,
    etaMinutes: 5.0,
    recommendedHospital: "Image Hospitals Madhapur",
    hospitalOccupancy: "Moderate",
    reasoning: "Patrol medic assigned to high-density intersection zone while traffic police manually direct flow.",
    confidenceScore: 91.0,
    status: "Pending",
  },
  {
    id: "REC-112",
    hazardId: "HZ-812",
    recommendedAmbulance: "Hazmat ALS Mobile Command H04",
    unitId: "AMB-H04",
    distanceKm: 5.2,
    etaMinutes: 8.4,
    recommendedHospital: "Gandhi General Hospital Hazmat Wing",
    hospitalOccupancy: "Moderate",
    reasoning: "Equipped with positive pressure respirators and chemical decontamination shower for chemical leak safety zone.",
    confidenceScore: 99.2,
    status: "Dispatched",
  },
  {
    id: "REC-113",
    hazardId: "HZ-813",
    recommendedAmbulance: "Standard BLS Unit B11",
    unitId: "AMB-B11",
    distanceKm: 1.5,
    etaMinutes: 3.0,
    recommendedHospital: "Sunshine Hospitals Gachibowli",
    hospitalOccupancy: "Low",
    reasoning: "Low priority standby unit staged near Raidurg metro interchange.",
    confidenceScore: 87.5,
    status: "Pending",
  },
  {
    id: "REC-114",
    hazardId: "HZ-814",
    recommendedAmbulance: "ALS Response Unit A09",
    unitId: "AMB-A09",
    distanceKm: 1.6,
    etaMinutes: 3.1,
    recommendedHospital: "Medicover Hospitals Hitec City",
    hospitalOccupancy: "Low",
    reasoning: "Unit A09 selected due to proximity and direct access via Inorbit Mall bypass road.",
    confidenceScore: 95.8,
    status: "Dispatched",
  },
  {
    id: "REC-115",
    hazardId: "HZ-815",
    recommendedAmbulance: "BLS Support Unit B02",
    unitId: "AMB-B02",
    distanceKm: 4.8,
    etaMinutes: 8.0,
    recommendedHospital: "KIMS Hospitals Begumpet",
    hospitalOccupancy: "Low",
    reasoning: "Routine clearance standby completed without victim transport required.",
    confidenceScore: 93.0,
    status: "Dispatched",
  },
];

export const MOCK_VERIFICATION_REPORTS: VerificationReport[] = [
  {
    id: "VR-501",
    hazardId: "HZ-801",
    duplicateDetectionScore: 96,
    confidenceScore: 96,
    sourceReliabilityScore: 98,
    fakeReportRiskScore: 2,
    crossVerificationSources: [
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:34:10" },
      { name: "Citizen Mobile App", status: "Verified", timestamp: "17:34:25" },
      { name: "Traffic Sensor IoT", status: "Verified", timestamp: "17:34:40" },
      { name: "911 Emergency Call", status: "Verified", timestamp: "17:35:02" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:34:00", details: "Multi-source signals detected on Gachibowli corridor." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:34:15", details: "Semantic extraction confirmed 2 buses and 1 sedan." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:34:35", details: "Speed drop to 0 km/h confirmed on IoT loop detectors." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:34:50", details: "3 duplicate phone calls merged into single incident HZ-801." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:35:10", details: "Verified P1 Critical status pushed to command grid." },
    ],
  },
  {
    id: "VR-502",
    hazardId: "HZ-802",
    duplicateDetectionScore: 98,
    confidenceScore: 98,
    sourceReliabilityScore: 95,
    fakeReportRiskScore: 1,
    crossVerificationSources: [
      { name: "Citizen Mobile App", status: "Verified", timestamp: "17:31:00" },
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:31:12" },
      { name: "Police Radio Dispatch", status: "Verified", timestamp: "17:31:45" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:31:00", details: "GPS tagged photo report uploaded via Citizen App." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:31:15", details: "Image model confirmed rollover vehicle at 99.4% confidence." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:31:30", details: "ORR speed telemetry anomaly detected." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:31:40", details: "No duplicate records detected." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:32:00", details: "Automated P1 dispatch recommendation issued." },
    ],
  },
  {
    id: "VR-503",
    hazardId: "HZ-803",
    duplicateDetectionScore: 91,
    confidenceScore: 91,
    sourceReliabilityScore: 92,
    fakeReportRiskScore: 4,
    crossVerificationSources: [
      { name: "Traffic Sensor IoT", status: "Verified", timestamp: "17:28:10" },
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:28:30" },
      { name: "Citizen Mobile App", status: "Pending", timestamp: "17:29:00" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:28:00", details: "Surface friction sensor alert at Cyber Towers underpass." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:28:20", details: "Camera feed detected oil slick reflection." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:28:45", details: "Motorcycle speed drop confirmed." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:29:10", details: "Clustered with minor skid report." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:29:30", details: "P2 High Priority confirmed." },
    ],
  },
  {
    id: "VR-504",
    hazardId: "HZ-804",
    duplicateDetectionScore: 99,
    confidenceScore: 99,
    sourceReliabilityScore: 99,
    fakeReportRiskScore: 1,
    crossVerificationSources: [
      { name: "911 Emergency Call", status: "Verified", timestamp: "17:25:05" },
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:25:20" },
      { name: "Police Radio Dispatch", status: "Verified", timestamp: "17:25:40" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:25:00", details: "High priority 911 dispatch audio stream ingested." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:25:15", details: "Audio speech-to-text extracted Mindspace junction location." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:25:30", details: "Intersection CCTV camera lock established." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:25:45", details: "Single call record confirmed." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:26:00", details: "Immediate P1 ALS dispatch triggered." },
    ],
  },
  {
    id: "VR-505",
    hazardId: "HZ-805",
    duplicateDetectionScore: 88,
    confidenceScore: 88,
    sourceReliabilityScore: 90,
    fakeReportRiskScore: 5,
    crossVerificationSources: [
      { name: "Police Radio Dispatch", status: "Verified", timestamp: "17:21:00" },
      { name: "Traffic Sensor IoT", status: "Verified", timestamp: "17:21:30" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:21:00", details: "Traffic officer radio chatter logged." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:21:20", details: "Stalled container truck identified." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:21:40", details: "Lane occupancy sensor continuous red." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:22:00", details: "Verified non-duplicate." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:22:20", details: "P3 Standard towing alert issued." },
    ],
  },
  {
    id: "VR-506",
    hazardId: "HZ-806",
    duplicateDetectionScore: 94,
    confidenceScore: 94,
    sourceReliabilityScore: 96,
    fakeReportRiskScore: 2,
    crossVerificationSources: [
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:18:10" },
      { name: "Citizen Mobile App", status: "Verified", timestamp: "17:18:30" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:18:00", details: "Thermal infrared video anomaly triggered." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:18:25", details: "Battery plume signature matched EV thermal alert." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:18:45", details: "Citizen app smoke photo matched." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:19:00", details: "Single event grouped." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:19:15", details: "P2 Hazmat unit recommended." },
    ],
  },
  {
    id: "VR-507",
    hazardId: "HZ-807",
    duplicateDetectionScore: 90,
    confidenceScore: 90,
    sourceReliabilityScore: 93,
    fakeReportRiskScore: 3,
    crossVerificationSources: [
      { name: "Traffic Sensor IoT", status: "Verified", timestamp: "17:14:00" },
      { name: "Police Radio Dispatch", status: "Verified", timestamp: "17:14:30" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:14:00", details: "Water pressure drop & acoustic road sensor alert." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:14:20", details: "Road surface erosion detected via pan-tilt camera." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:14:40", details: "Flow diverted." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:15:00", details: "No duplicate." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:15:20", details: "P2 road closure alert verified." },
    ],
  },
  {
    id: "VR-508",
    hazardId: "HZ-808",
    duplicateDetectionScore: 97,
    confidenceScore: 97,
    sourceReliabilityScore: 97,
    fakeReportRiskScore: 1,
    crossVerificationSources: [
      { name: "Citizen Mobile App", status: "Verified", timestamp: "17:11:00" },
      { name: "CCTV AI Vision", status: "Verified", timestamp: "17:11:20" },
      { name: "911 Emergency Call", status: "Verified", timestamp: "17:11:45" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:11:00", details: "4 phone calls & photo uploads received." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:11:20", details: "Multi-vehicle impact visual confirmed." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:11:40", details: "Bio-Diversity ramp traffic lock." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:12:00", details: "Merged 4 reports into HZ-808." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:12:15", details: "P1 Multi-patient unit assigned." },
    ],
  },
  {
    id: "VR-509",
    hazardId: "HZ-809",
    duplicateDetectionScore: 85,
    confidenceScore: 85,
    sourceReliabilityScore: 88,
    fakeReportRiskScore: 6,
    crossVerificationSources: [
      { name: "Police Radio Dispatch", status: "Verified", timestamp: "17:06:00" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:06:00", details: "Traffic patrol radio report." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:06:30", details: "Obstruction size estimated at 3m x 1m." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:07:00", details: "Vehicle slowdown confirmed." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:07:15", details: "No duplicate." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:07:30", details: "P3 Moderate priority tagged." },
    ],
  },
  {
    id: "VR-510",
    hazardId: "HZ-810",
    duplicateDetectionScore: 95,
    confidenceScore: 95,
    sourceReliabilityScore: 98,
    fakeReportRiskScore: 2,
    crossVerificationSources: [
      { name: "911 Emergency Call", status: "Verified", timestamp: "17:02:00" },
      { name: "Citizen Mobile App", status: "Verified", timestamp: "17:02:20" },
    ],
    verificationTimeline: [
      { stage: "Report Ingestion", status: "completed", timestamp: "17:02:00", details: "Emergency call from bus driver." },
      { stage: "NLP & Computer Vision Analysis", status: "completed", timestamp: "17:02:20", details: "Medical terms 'cardiac', 'unconscious' identified." },
      { stage: "Cross-Sensor Validation", status: "completed", timestamp: "17:02:40", details: "GPS bus location matched Miyapur exit." },
      { stage: "Duplicate Deduplication", status: "completed", timestamp: "17:03:00", details: "Driver & passenger calls linked." },
      { stage: "Dispatcher Verification Signal", status: "completed", timestamp: "17:03:15", details: "P2 Cardiac ALS dispatched." },
    ],
  },
];

export function parseEmergencyReportMock(reportText: string): ParsedIncident {
  const lower = reportText.toLowerCase();

  let incidentType = "Vehicle Collision";
  if (lower.includes("bus") || lower.includes("buses")) incidentType = "Multi-Bus Crash";
  else if (lower.includes("fire") || lower.includes("smoke") || lower.includes("burn")) incidentType = "Vehicle Thermal Incident";
  else if (lower.includes("spill") || lower.includes("oil")) incidentType = "Hazardous Material Spill";
  else if (lower.includes("pedestrian") || lower.includes("struck")) incidentType = "Pedestrian Injury";
  else if (lower.includes("cardiac") || lower.includes("heart") || lower.includes("unconscious")) incidentType = "Medical Emergency";
  else if (lower.includes("rollover") || lower.includes("flip")) incidentType = "Rollover Accident";

  let severity: ParsedIncident["severity"] = "High";
  if (lower.includes("immediately") || lower.includes("critical") || lower.includes("trapped") || lower.includes("heavy")) severity = "Critical";
  else if (lower.includes("minor") || lower.includes("stalled")) severity = "Low";
  else if (lower.includes("moderate") || lower.includes("slow")) severity = "Moderate";

  let priority: ParsedIncident["priority"] = "P2 - High";
  if (severity === "Critical") priority = "P1 - Immediate";
  else if (severity === "Moderate") priority = "P3 - Standard";
  else if (severity === "Low") priority = "P4 - Low";

  let location = "Gachibowli Flyover Corridor, Hyderabad";
  if (lower.includes("hitec") || lower.includes("cyber")) location = "Hitec City Cyber Towers Junction";
  else if (lower.includes("orr") || lower.includes("ring road") || lower.includes("narsingi")) location = "Outer Ring Road Exit 3 Interchange";
  else if (lower.includes("jubilee") || lower.includes("road 36")) location = "Jubilee Hills Road No. 36";
  else if (lower.includes("kondapur") || lower.includes("botanical")) location = "Kondapur Main Road near Botanical Gardens";
  else if (lower.includes("mindspace")) location = "Mindspace IT Park Signal 2";
  else if (lower.includes("miyapur")) location = "Miyapur Metro Station Depot Exit";

  let vehiclesInvolved = "2 Vehicles";
  if (lower.includes("two buses") || lower.includes("2 buses")) vehiclesInvolved = "2 Commercial Buses";
  else if (lower.includes("suv")) vehiclesInvolved = "1 SUV";
  else if (lower.includes("truck")) vehiclesInvolved = "1 Heavy Freight Truck";
  else if (lower.includes("auto")) vehiclesInvolved = "1 EV Auto Rickshaw";
  else if (lower.includes("bike") || lower.includes("motorcycle")) vehiclesInvolved = "2 Motorcycles";

  let blockedLanes = "2 Lanes Blocked";
  if (lower.includes("all lanes") || lower.includes("closed")) blockedLanes = "All Arterial Lanes Blocked";
  else if (lower.includes("shoulder")) blockedLanes = "Right Emergency Shoulder";
  else if (lower.includes("1 lane") || lower.includes("single lane")) blockedLanes = "1 Far Left Lane";

  let victimsEstimated = 2;
  if (lower.includes("5") || lower.includes("five")) victimsEstimated = 5;
  else if (lower.includes("3") || lower.includes("three")) victimsEstimated = 3;
  else if (lower.includes("4") || lower.includes("four")) victimsEstimated = 4;
  else if (lower.includes("1") || lower.includes("one")) victimsEstimated = 1;
  else if (lower.includes("none") || lower.includes("no victim")) victimsEstimated = 0;

  let weatherImpact = "Clear visibility, dry pavement surface";
  if (lower.includes("rain") || lower.includes("wet") || lower.includes("water")) weatherImpact = "Wet asphalt, 15% traction reduction";
  else if (lower.includes("night") || lower.includes("dark")) weatherImpact = "Low ambient light, high headlight glare";

  // Parsing output is rendered during SSR, so it must be stable for identical
  // reports. Keep the mock confidence deterministic instead of simulating it.
  const confidenceScore = 96;

  return {
    incidentType,
    severity,
    location,
    vehiclesInvolved,
    blockedLanes,
    victimsEstimated,
    weatherImpact,
    confidenceScore,
    priority,
    rawReport: reportText,
    parsedAt: "Deterministic mock analysis",
  };
}
